added API support for IOC
oceanmodeling/searvey pull request #100
Opened 2023-08-03 11:43 UTC by tomsail

implemented the API requests through IOC, using the query flag. See [Issue #47](https://github.com/oceanmodeling/searvey/issues/47)

Extraction is significantly faster.

The most significant change being: 
* the main channel (parameter "sensor": reference [here](https://www.ioc-sealevelmonitoring.org/service.php?query=help) and example [here](https://www.ioc-sealevelmonitoring.org/service.php?query=data&format=json&code=audi&timestart=2022-01-01T00:00&timestop=2023-01-01T00:00)) is being automatically renamed 'slevel' and all other channels are ignored.

More testing might be needed

2023-08-03 12:34 UTC, pmav99 requested changes
Some of the `_api()` functions don't seem to have any differences. If you intend to update them, then for sure keep them, but if they are going to be the same I would just reuse the existing ones.

2023-08-03 12:34 UTC, pmav99 commented on searvey/ioc.py
> +IOC_STATIONS_COLUMN_NAMES_API = {
is this being used? Maybe it is a placeholder to be used by line 197?

2023-08-03 12:34 UTC, pmav99 commented on searvey/ioc.py
> +        # fmt: off
The `fmt` comments here seem to be redundant. We do use them in lines 202-207 but there we are exceeding the maximum line length and we want to suppress the error in `black`.

2023-08-03 12:34 UTC, pmav99 commented on searvey/ioc.py
> +        observations_ratio_per_month=df.observations,
I think that with this line we will end up with two identical columns: `observations` and `observations_ratio_per_month`.

If we want to only change the name, then `df = df.rename({...})` should be prefered.

 `df = df.assign(...)` is used for creating new columns and/or applying some transformation on a existing column. E.g.
 ``` python
 df = df.assign(gloss_id=df.gloss_id.astype(int)) # we are changing the data type and replacing the existing column
 ```

2023-08-03 12:34 UTC, pmav99 commented on searvey/utils.py
> +ONEMONTHAGO: Final = "ONEMONTHAGO"
Is this being used?

2023-08-07 19:13 UTC, pmav99 commented
The tests are failing due to reduced test coverage. We can change the minimum required threshold in pyproject.toml, but we do need to add some tests for the new API, too.

2023-08-09 08:47 UTC, tomsail commented
I'll look into adding a test later this week. I'll reuse when I am doing now to extract and concatenate years of data.

2023-09-05 09:24 UTC, tomsail commented
> The tests are failing due to reduced test coverage. We can change the minimum required threshold in pyproject.toml, but we do need to add some tests for the new API, too.

I have added the test for the API

2024-06-26 10:24 UTC, pmav99 commented
Superseded by #125

2024-06-26 10:24 UTC, closed without merging